name : colortest-reverse
game_class : ReverseColorTestGame
author: MKR
version: 1.0
tags:
  - visual
  - attention
scripts:
styles:
resources:
settings:
locales:
  - en:
    - title: Color Reaction Test
    - subtitle: " "
    - description: " "
    - instructions: Choose the colored square which matches the color of the text appearing in the center of the screen as fast as possible.
  - cz:
    - title: Reakční test  – barvy
    - subtitle: " "
    - description: " "
    - instructions: Zvolte vždy co nejrychleji čtverec se shodnou barvou, jakou má nápis, který se objeví uprostřed.
gamepacks:
    - name : default
      settings:
      resources:
      locales:
        - en:
        - cz:
