name : questionary
game_class : Questionary
author: MKR
version: 1.0
tags:
  - survey
locales:
  - en:
    - title:        Questionary
    - subtitle:     " "
    - description:  " "
    - instructions: " "
  - cz:
scripts:
styles:
resources:
settings:
gamepacks:
    - name : barthel-en
      locales:
        - en:
          - title:        Barthel Index
          - subtitle:     " "
          - description:  " "
          - instructions: |
                The Barthel scale or Barthel ADL index is an ordinal scale used to measure performance in activities of daily living. Each performance item is rated on this scale with a given number of points assigned to each level or ranking. The maximum score corresponds to full independence - the patient does not need help at all, not even verbal cues.

                Dependency score:

                0-20 points: total dependency
                21-60 points: dependency
                61-90 points: moderate dependency
                91-99 points: slight dependency
                100 points: independency
      resources:
        - questionary:  questionary.json
    - name : barthel-cz
      locales:
        - cz:
          - title:        Barthel Index
          - subtitle:     " "
          - description:  " "
          - instructions: |
                Barthel Index je standardizovaný test určený k hodnocení soběstačnosti. Body jsou přidělovány podle toho, co pacient reálně dokáže. Plný počet bodů vylučuje i jen minimální pomoc, včetně nápovědy. Pacient může při hodnocených činnostech využívat mechanické pomůcky (madla na stěnách, hole, berle apod.).

                Hodnocení soběstačnosti:

                0-40 bodů	vysoce závislý
                45-60 bodů	závislost středního stupně
                65-95 bodů	lehká závislost
                100 bodů	nezávislý
      resources:
        - questionary:  questionary.json
